insert into `products_genres` (`genre_id`, `product_id`) values (1, 2);
insert into `products_genres` (`genre_id`, `product_id`) values (1, 3);
insert into `products_genres` (`genre_id`, `product_id`) values (2, 27);
insert into `products_genres` (`genre_id`, `product_id`) values (6, 3);
insert into `products_genres` (`genre_id`, `product_id`) values (7, 27);
insert into `products_genres` (`genre_id`, `product_id`) values (9, 2);
insert into `products_genres` (`genre_id`, `product_id`) values (9, 3);
insert into `products_genres` (`genre_id`, `product_id`) values (9, 26);
insert into `products_genres` (`genre_id`, `product_id`) values (9, 28);
